modLoader="javafml"
loaderVersion="[39,)"
license="MIT"
[[mods]]
modId="createtweaker"
version="${file.jarVersion}"
displayName="CreateTweaker"
updateJSONURL="https://updates.blamejared.com/get?n=createtweaker&gv=1.18.2"
authors="Jaredlll08"
description='''
Adds CraftTweaker support to Create
'''

[[dependencies.createtweaker]]
modId = "create"
mandatory = true
versionRange = "[0.5,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.createtweaker]]
modId = "crafttweaker"
mandatory = true
versionRange = "[9.1.192,)"
ordering = "NONE"
side = "BOTH"